ind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    deployment.kubernetes.io/revision: '2'
  name: static-nodejs-app
  namespace: myappcontainers
  labels:
    app: static-nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-nodejs-app
  template:
    metadata:
      labels:
        app: static-nodejs-app
        deploymentconfig: static-nodejs-app
    spec:
      containers:
        - name: static-nodejs-app
          image: vikashforsrm/nodejs-docker-static-app:latest
          ports:
            - containerPort: 3000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: static-nodejs-app-svc
spec:
  selector:
    app: static-nodejs-app
  portalIP:
  ports:
  - nodePort: 0
    port: 3000
    protocol: TCP
    targetPort: 3000
---
apiVersion: v1
kind: Route
metadata:
  name: static-nodejs-app-route
spec:
  host:
  path: "/"
  to:
    kind: Service
    name: static-nodejs-app-svc
